
language: python
python:
  #- "2.6"
  - "2.7"
# prepare environment
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgd2-xpm-dev libgif-dev
# command to install dependencies
install:
  - pip install .
# command to run tests
script: nosetests
